### ISSUE TITLE
请问cookie怎么抓

### ISSUE THREAD

**Issue by sonrixmomo** [AlanLang/hifini-auto-sign-in#1]
我抓不到cookie

**Comment by AlanLang** [comment]
谷歌浏览器登录hifini后, F12打开控制台:
![image](https://user-images.githubusercontent.com/33884749/112564034-7b5bc000-8e15-11eb-83ec-8b14ffc532ed.png)

**Comment by sonrixmomo** [comment]
> 谷歌浏览器登录hifini后, F12打开控制台:
> ![image](https://user-images.githubusercontent.com/33884749/112564034-7b5bc000-8e15-11eb-83ec-8b14ffc532ed.png)

感谢大佬
